wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
    - 1: loss_kl/train
      5: 1
      6:
      - 1
      - 3
    - 1: loss_kl/val
      5: 1
      6:
      - 1
      - 3
    - 1: loss/test
      5: 1
      6:
      - 1
      - 3
    - 1: loss_kl/test
      5: 1
      6:
      - 1
      - 3
    - 1: loss/val
      5: 1
      6:
      - 1
      - 3
    - 1: auc/val
      5: 1
      6:
      - 1
      - 3
    - 1: ap/val
      5: 1
      6:
      - 1
      - 3
    python_version: 3.8.13
    start_time: 1668854940
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 50
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      3:
      - 7
      - 16
      4: 3.8.13
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 32
beta:
  desc: null
  value: 10
heads:
  desc: null
  value: 1
latent_channels:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 3
