wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1667857246
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      3:
      - 16
      4: 3.8.13
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 32
beta:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 300
latent_channels:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.01
num_layers:
  desc: null
  value: 3
